# Form implementation generated from reading ui file './ui/new_car.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.carMark_label = QtWidgets.QLabel(parent=Form)
        self.carMark_label.setMinimumSize(QtCore.QSize(80, 31))
        self.carMark_label.setMaximumSize(QtCore.QSize(16777215, 31))
        self.carMark_label.setObjectName("carMark_label")
        self.horizontalLayout.addWidget(self.carMark_label)
        self.carMark_lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.carMark_lineEdit.setMinimumSize(QtCore.QSize(0, 31))
        self.carMark_lineEdit.setMaximumSize(QtCore.QSize(16777215, 31))
        self.carMark_lineEdit.setObjectName("carMark_lineEdit")
        self.horizontalLayout.addWidget(self.carMark_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gosNum_label = QtWidgets.QLabel(parent=Form)
        self.gosNum_label.setMinimumSize(QtCore.QSize(80, 31))
        self.gosNum_label.setMaximumSize(QtCore.QSize(16777215, 31))
        self.gosNum_label.setObjectName("gosNum_label")
        self.horizontalLayout_2.addWidget(self.gosNum_label)
        self.gosNum_lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.gosNum_lineEdit.setMinimumSize(QtCore.QSize(0, 31))
        self.gosNum_lineEdit.setMaximumSize(QtCore.QSize(16777215, 31))
        self.gosNum_lineEdit.setObjectName("gosNum_lineEdit")
        self.horizontalLayout_2.addWidget(self.gosNum_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.changeOwner_label = QtWidgets.QLabel(parent=Form)
        self.changeOwner_label.setMinimumSize(QtCore.QSize(231, 31))
        self.changeOwner_label.setObjectName("changeOwner_label")
        self.horizontalLayout_3.addWidget(self.changeOwner_label)
        self.changeOwner_lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.changeOwner_lineEdit.setMinimumSize(QtCore.QSize(0, 31))
        self.changeOwner_lineEdit.setObjectName("changeOwner_lineEdit")
        self.horizontalLayout_3.addWidget(self.changeOwner_lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.changeOwner_listView = QtWidgets.QListView(parent=Form)
        self.changeOwner_listView.setObjectName("changeOwner_listView")
        self.verticalLayout_2.addWidget(self.changeOwner_listView)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.add_pushButton = QtWidgets.QPushButton(parent=Form)
        self.add_pushButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.add_pushButton.setObjectName("add_pushButton")
        self.horizontalLayout_4.addWidget(self.add_pushButton)
        self.close_pushButton = QtWidgets.QPushButton(parent=Form)
        self.close_pushButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.close_pushButton.setObjectName("close_pushButton")
        self.horizontalLayout_4.addWidget(self.close_pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Добавление автомобиля"))
        self.carMark_label.setText(_translate("Form", "Марка авто:"))
        self.gosNum_label.setText(_translate("Form", "Гос. номер:"))
        self.changeOwner_label.setText(_translate("Form", "Выберите собственника из списка:"))
        self.add_pushButton.setText(_translate("Form", "Добавить"))
        self.close_pushButton.setText(_translate("Form", "Закрыть"))
